name: "Zizmor CI"
description: "Run zizmor"
inputs:
  working-directory:
    default: "."
    description: "The working directory"
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false

    - uses: actions/setup-python@v5
      with:
        python-version: 3.13

    - run: pip install zizmor
      shell: bash

    - run: zizmor .
      shell: bash
      working-directory: ${{ inputs.working-directory }}
